callsAbandonedReport;
callsAutomaticDailyByIntervalReport;
callsAutomaticDailyReport;
callsDetailReport;

callsInboundDailyByIntervalReport;
callsInboundDailyReport;
callsOutboundDailyByIntervalReport;
callsOutboundDailyReport;
callsWaitTimeReport;
